# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 22.22.22.22 - Target staging server's IP address
# 33.33.33.33 - Second worker node in this 2-server setup
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    # @todo how many days to store backups for?
    amount_of_backups_to_keep: 7
    backup_server_remote_target_directory: /home/backup/backups
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: roger
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyrNJ3IDCc4fdjF6u40/T8u/VKQxF1x1U0GwIEhdoWfjK4yklJ05QzTLFjNba8gyCBMLiinvRwY8hn8BzIQHeXhpdaa26b6zvJg5O8G1Ly5C5htWXQj3mD/KVDPt3Gu4EmR2Ycq9qCXINPO0t62C6lSF9rOiVXW3aWdPc+sSNTUT7Pxpa2INDS2hiV7bKWO/JZngjFJzMWguYc7xUtGozUhCbxA2hciUxlXfIfIsid0tm4wDRH1sN3IicoXiqCVWrq0abkISJJOHvQ9eUfaSTUc4P0P5gxepi+T1u0S3RrghhyaOUXGfMU6nWjZIICfTtXzStDBLE16LTOBx0V3+8Gx/Ro6SjWM5gBDp2dpqQX4y4Cs29EvSSEup9if4DmcXTNMYMo/C0nTDXCu8G/KXzvH1/DBOlB3zJ7MGgZ5G2OgLLijVCXmaIc/XzB0wu5PWcXU1DanDZRwLggfuAFIRDjXBDMzBgurjq8HQCEEFNTOpSLUyTITTFnyhXT/ru5Hps= roger@roger-Dell-G15-5530
        state: present
        sudoer: true
      - name: tameem
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGUprcQyUFYwRto0aRpgriR95C1pgNxrQ0lEWEe1D8he haidertameem@gmail.com
        state: present
        sudoer: true

backups-host:
  hosts:
    opencrvs-backup: # @todo set this to be the hostname of your backup server
      ansible_host: '10.40.0.113'
